#! /bin/bash

folders=`ls motifs`

for folder in $folders
do
   for (( c=3; c<=20; c++ ))
      do
         meme \
            -searchsize 0 \
            -protein -objfun classic \
            -oc "motifs/${folder}/${c}_${c}" \
            -mod zoops -minw ${c} -maxw ${c} -nmotifs 100 \
            -minsites 23 -evt 0.05 \
            -p '10 --use-hwthread-cpus' \
            "fasta_cleaned/all_${folder}.fasta"
      done
done
