#! /bin/bash

folders=`ls motifs_cleaned`

for folder in $folders
do
   for (( c=3; c<=20; c++ ))
   do
      meme -protein -objfun classic -oc "motifs_cleaned/${folder}/${c}_${c}" -mod oops -minw $c -maxw $c -nmotifs 50 motifs_cleaned/${folder}/all_*.fasta -p '16 --use-hwthread-cpus'
   done
done

folders=`ls motifs`

for folder in $folders
do
   for (( c=3; c<=20; c++ ))
   do
      meme -protein -objfun classic -oc "motifs/${folder}/${c}_${c}" -mod oops -minw $c -maxw $c -nmotifs 50 motifs/${folder}/all_*.fasta -p '16 --use-hwthread-cpus'
   done
done
